services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tydee-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Tydee_Dev123!
    volumes:
      - mssql-data:/var/opt/mssql
    ports:
      - 1433:1433

  seq:
    image: datalust/seq:2024.3
    container_name: tydee-seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80

volumes:
  mssql-data:
